{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  # TODO: Replace with hardware configuration generated by `nixos-generate-config` for your desktop.
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  hardware.opengl = {
    enable = true;
    driSupport32Bit = true;
    extraPackages = with pkgs; [
      amdvlk
      vaapiVdpau
      libvdpau-va-gl
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      amdvlk
    ];
  };

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  swapDevices = [
    {
      device = "/swapfile";
      size = 48 * 1024;
    }
  ];
}
