{ config, lib, pkgs, modulesPath, ... }:
{
  # TODO: Replace with hardware configuration generated by `nixos-generate-config` for your desktop.
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
}
